### ISSUE TITLE
How to hide the SayDialog?

### ISSUE THREAD

**Issue by VaultKid** [maurovanetti/inkfungus-template#12]
Is there a way to hide the SayDialog? Pause- and stop-events only stop the narrative from going on and the SayDialog window is still kept on my screen.
I also tried to write my own fungus command to deactivate the SayDialog, but that didn't worked either.

Thanks in advance for the help. I bet I just overlooked the feature somewhere. :)

**Comment by maurovanetti** [comment]
Hello!
The #pause event should actually hide the SayDialog, with the latest release (v1.1.1) at least. But Ink has some intricacies that made me struggle in some edge cases (such as one-line knots with #pause, etc.).
Can you give me some more context? The .ink source file would be great.
Thank you for your help in improving this tool.

**Comment by VaultKid** [comment]
Hello! 
I am on Ink-Fungus Gateway 1.1.1 and Fungus 3.13.4.

I had to upload the file as a .txt. Just remove the file extension.
"load-sushi-game" in line 35 loads another scene which jumps to line 39 "sushiGame1" and resumes the narrative

[demo.ink.txt](https://github.com/maurovanetti/inkfungus-template/files/8854859/demo.ink.txt)

**Comment by VaultKid** [comment]
I created a test project with nothing but the ink file and #pause works perfectly there. I guess it's an issue with something else I got running in my original project. I gonna let you know when I find the problem.

**Comment by VaultKid** [comment]
My workaround was to export all assets, create a new project and import all assets there. Now it works perfectly fine. 😅

**Comment by maurovanetti** [comment]
This is… interesting. :smile: 
I have really no idea what could have caused this. Thank you very much for letting me know in any case, if I see something similar happening again I can study it more.
Have fun!
